#!/bin/bash

# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

test -f .env && source $_

set -e

BASE_DIR=$(readlink -m "$(dirname "${BASH_SOURCE[0]}")")
MANIFEST="${BASE_DIR}/manifests/deps.xml"

mkdir -p deps
pushd $_
repo init --standalone-manifest --manifest-url="file://${MANIFEST}" ${BOLT_REPO_INIT_PARAMS}
repo sync ${BOLT_REPO_SYNC_PARAMS}

# v3.38.3 : apply backported fix to enable flutter-engine compilation on arm64 host
git -C meta-flutter apply ${BASE_DIR}/repo-patches/backport-cfc0d7d5d831a238ab7b9bc21f66fbb6af3c1984.patch
# 3.38.3 : forcefully disable openjdk fetch (doesn't work on arm64 host)
git -C meta-flutter apply ${BASE_DIR}/repo-patches/disable_jdk.patch

popd
